/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'j.yadav' at '9/13/16 1:29 PM' with Gradle 2.9
 *
 * @author j.yadav, @date 9/13/16 1:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
